sudo: required
language: go
os: windows
services:
- docker
go:
- 1.11.x
env:
  global:
  - GO111MODULE=on
cache:
  directories:
  - $GOPATH/pkg/mod
install: true
script:
- go build -o artifacts/pack-$TRAVIS_BUILD_NUMBER-windows ./cmd/pack
- PACK_PATH=$PWD/artifacts/pack-$TRAVIS_BUILD_NUMBER-windows go test -parallel 1 -v ./...
